### ISSUE TITLE
Use map-reduce instead of for-loops?

### ISSUE THREAD

**Issue by namratachaudhary** [arjun27/advent-of-code-clojure#2]
https://github.com/arjun27/advent-of-code-clojure/blob/d7bcaafabfc852f811d7d6cd7dbec741fdd46b4f/src/puzzle1.clj#L12

Just more functional, since you're writing clojure. I'd do it something like - 

```
(def data (map read-string input))

(defn part-1 []
  (reduce + data))
```

**Comment by arjunattam** [comment]
ah yeah much better. making this change
